//-----------------------------------------------------------------------------
// FILE:        Program.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:   Copyright (c) 2005-2015 by Jeffrey Lill. All rights reserved.
// DESCRIPTION: It slices, it dices, it make jullienne fries!

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;

using LillTek.Common;

namespace LillTek.Tools.Vegomatic
{
    /// <summary>
    /// It slices, it dices, it make jullienne fries!  This tools performs
    /// various random tasks.
    /// </summary>
    /// <remarks>
    /// <code language="none">
    /// Usage: vegomatic [-out:&lt;file&gt;] &lt;command&gt; &lt;cmdarg0&gt; &lt;cmdarg1&gt;...
    /// 
    /// Commands
    /// --------
    /// 
    ///     vegomatic text ...       - TEXT related commands
    ///     vegomatic file ...       - Misc file utilities
    ///     vegomatic crypto ...     - Cyptographic utilities
    ///     vegomatic zip ...        - ZIP Archive creation
    ///     vegomatic unzip ...      - ZIP Archive extraction
    ///     vegomatic auth ...       - Authentication Service commands
    ///     vegomatic pack ...       - Application Package commands
    ///     vegomatic appstore ...   - Application Store commands
    ///     vegomatic ini ...        - INI file manipulation commands
    ///     vegomatic helpmunge...   - Munges code documentation help files
    ///     vegomatic silverlight... - Extended web service proxy generator
    ///                                for Silverlight applications
    ///     vegomatic linq2sql...    - Munges LINQ to SQL source files
    ///                                generated by SQLMetal
    /// 
    /// Options
    /// -------
    /// 
    /// -out:&lt;file&gt;     Redirects standard output to this file. Using this
    ///                 option allows progress status to be written to the
    ///                 console window.
    /// 
    /// The application will also create a file called ""vegomatic.log"" 
    /// in the current directory where certain commands will write summarizes 
    /// of what happened.
    ///
    /// -ep:&lt;multicast-ep&gt;  Specifies the LillTek Messaging UDP multicast 
    ///                     endpoint to be used when transmitting the messages.
    ///                     This is expressed as &lt;dotted-quad&gt;:&lt;port&gt;
    ///                     (see the LillTek Messaging note below).
    /// 
    /// The application will also create a file called ""vegomatic.log"" 
    /// in the current directory where certain commands will write summarizes 
    /// of what happened.
    /// 
    /// LillTek Messaging
    /// -----------------
    /// Some vegomatic commands need route messages via the LillTek Messaging
    /// layer.  For this to work properly, vegomatic needs to know the 
    /// UDP multicast endpoint to use for discovering the other messaging
    /// nodes on the network.
    /// 
    /// This multicast endpoint can be specified explicitly via the
    /// -ep:&lt;multicast-ep&gt; option.  If this option is not present, then
    /// the command will look for the MsgRouter.CloudEP setting in
    /// the local configuration file or in the file referenced by the 
    /// LillTek.ConfigOverride environment variable if present.  Otherwise, 
    /// the default endpoint specified by LillTek.Const.DCCloudEP will 
    /// be used.
    /// </code>
    /// </remarks>
    public static class OverviewDoc
    {
    }

}

